config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :posts
    post "posts/new", to: "posts#create", as: :new_post
  end
  resources :posts do
    resources :comments
  end

  devise_for :users
  root to: 'groups#index'
  resources :user_groups
  end

app/models/group.rb
class Group < ApplicationRecord
    has_many :user_groups
    has_many :users, through: :user_groups
    has_many :posts

    validates :name, presence: true

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[ show edit update destroy ]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
    @post = Post.new
    @users = User.joins(:user_groups).where(user_groups: {group_id: @group.id})
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to root_path, notice: "Group was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_update_params)
        format.html { redirect_to group_url(@group), notice: "Group was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: "Group was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_params
      params.permit(:name)
    end
    def group_update_params
      params.require(:group).permit(:name)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: @group, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.text_field :name, placeholder: "Enter Group name", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/groups/_links.html.erb
<div class="relative flex h-16 items-center justify-between ">
  <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
    <button class= "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> All Groups </button>
    <button class= "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> My groups </button>
    <button class= "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %> Joined groups </button>
  </div>
    
  <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
    <div data-controller="modal">
      <button data-action="modal#open" class="rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium">New Group</button>
      <dialog data-modal-target="modal">
        <button type="button" data-action="modal#close" class="absolute top-4 right-4">X</button>
        <%= render template: "groups/new" %>
      </dialog>
    </div>
  </div>
</div>

app/views/groups/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing group</h1>

  <%= render "form", group: @group %>
  
</div>

app/views/groups/index.html.erb
<div class="container mx-auto mt-10 px-5 mx-auto w-full">
  <div class="mb-6">
    <h1 class="font-bold text-4xl">Groups</h1>
  </div>

  <%= render partial: "groups/links"%>

  <div id="groups" class="min-w-full mt-6">
    <div class="container mx-auto mt-10 px-5 mx-auto w-full">
      <% @groups.each do |g|  %>
        <div class="flex mx-auto mt-10 mx-auto w-full justify-between rounded shadow-lg p-3">

          <div >
            <h2 class ="text-2xl mb-2"><%=link_to g.name, group_path(g.id)%></h2>
            <div class="flex gap-7">
              <p class="mr-4">Members: <%=g.users.size%></p>
              <p class="mr-4">Posts:<%= g.posts.size%></p>
              <% if !defined?(g.posts.last.updated_at)%>
                <p>No Activity</p>           
              <%else%>
                <p>Last Activity: <%=distance_of_time_in_words(g.posts.last.updated_at, DateTime.now)%></p>
              <%end%>
            </div>
          </div>
          <div >
            <% if !defined?(g.user_groups.last.status)%>
            <%= form_for UserGroup.new do |f| %>
              <%= f.text_field :user_id, type: "hidden", value: current_user.id %>
              <%= f.text_field :group_id, type: "hidden", value: g.id%>
              <%= f.text_field :status, type: "hidden", value: true %>
              <%= f.submit "Join", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>          
            <%end%>
            <%else%>

            <%= button_to 'Leave', user_group_path(g.id), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h2 class="font-bold text-4xl">New group</h2>
  <%= render "form", group: @group %>
</div>

app/views/groups/show.html.erb
<div class="container mx-auto mt-10 px-5 mx-auto w-full">
  <div class="flex ">
    <div class="mx-auto md:w-2/3 w-full ">
      <div class="mx-auto">
        <div class="mb-6 flex justify-between">

          <h1 class="font-bold text-4xl"><%= @group[:name] %></h1>
          <div data-controller="modal">

            <button data-action="modal#open" class="rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium">Edit group</button>
            <dialog data-modal-target="modal">

              <button type="button" data-action="modal#close" class="absolute top-4 right-4">X</button>
              <%= render template: "groups/edit" %>

            </dialog>
          </div>
        </div>
      <div>
        <%= render template: "posts/new"%>
      </div>
    </div>
    
    <div>
      <h1 class="font-bold text-2xl mb-4">All Posts</h1>
      <%= render(PostComponent.new(post: @posts)) %>
    </div>
  </div>
  <div class="ml-2 flex flex-col w-1/5 mt-16">
    <h2 class="text-2xl">Members</h2>
    <% @users.each do |user| %>
      <%= user.email[/^[^@]+/] %>
    <%end%>
  </div>
</div>