config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :posts
    post "posts/new", to: "posts#create", as: :new_post
  end
  resources :posts do
    resources :comments
  end

  devise_for :users
  root to: 'groups#index'
  resources :user_groups
  end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :comments, dependent: :destroy
  
    validates :title, presence: true
    validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :get_groups

  # GET /posts or /posts.json
  def index
    @posts = @group.posts
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = @group.posts.build
    @user = current_user
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = @group.posts.build(post_params)
    @post.user = current_user
    @post.group = Group.find(params[:group_id])

    respond_to do |format|
      if @post.save
        format.html { redirect_to group_path(@group), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to group_path(@group), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to group_path(@group), notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def get_groups
      @group = Group.find(params[:group_id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing post</h1>

  <%= render "form", post: @post %>

  <%= link_to "Back to posts", group_posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Posts</h1>
    <%= link_to 'New post', new_group_post_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= link_to 'Show Group', [@group]%>

  <div id="posts" class="min-w-full">
    <%= render(PostComponent.new(post: @posts)) %>
    

  </div>
</div>

app/views/posts/new.html.erb
<div class="flex flex-col"> 
<%= form_with model: @post, url: new_group_post_path(params[:id]), class: "contents" do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "Write your title"%>
    <%= form.text_area :content,  class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full h-48 mb-4 post-placeholder", placeholder: "Write your post" %>
</div>
    <%= form.submit class: " self-end rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="container mx-auto mt-10 px-5 mx-auto w-full">
  <div class="flex flex-col w-4/5">
      <div class="font-bold text-4xl mb-4 "><%= @post.title%></div>
      <div><%= @post.content%></div>
    </div>

    <div>
    <hr/>
      <div class="font-bold text-2xl mb-4"> Comments </div>
      <div class="">
        <%= render @post.comments.where(parent_id:nil).includes(:user).order(id: :desc).limit(10) %>
      </div>
      <%= render partial: 'comments/form', locals: {post: @post, parent: nil} %>

  </div>
</div>